---

  - name: Create a directory .ssh
    file:
      path: /root/.ssh
      state: directory
      mode: '0700'



  
  - name: Copy id_rsa ans authorized_keys
    copy:
      src: files/keys/
      dest: /root/.ssh/
      owner: root
      group: root
      mode: '0600'


  - name: restart sshd
    systemd:
      name: sshd
      state: restarted



  

  - name: Add repo postgresql
    yum:
     name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
     state: present      
      

  - name: Add repo mamonsu
    yum:
     name: https://repo.postgrespro.ru/mamonsu/keys/centos.rpm
     state: present      
      


  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: Устанавливаем  epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install package
    yum:
     name:
      - net-tools
      - vim
      - zip
      - unzip
      - traceroute
      - mtr
      - mc
      - tcpdump
      - python-psycopg2
      - postgresql13-server
      - mamonsu





  - name: Инициализируем бд
    shell: postgresql-13-setup initdb
    ignore_errors: yes
    


  - name: Copy pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest: /var/lib/pgsql/13/data/
      owner: postgres
      group: postgres
      mode: '0744'


  - name: Copy postgresql.conf
    template:
      src: postgresql.conf.j2
      dest: /var/lib/pgsql/13/data/
      owner: postgres
      group: postgres
      mode: '0744'




  - name: start postgresql
    systemd:
      name: postgresql-13
      state: started
      enabled: yes



  - name: Create database users
    postgresql_user:
        db: postgres
        name: root
        password: B29z3z4z4z1
        role_attr_flags: SUPERUSER,LOGIN
    become: yes
    become_user: postgres
    with_items:
        - { name: "{{ barman_username }}", password: "{{ barman_password }}", flags: SUPERUSER}
        - { name: "{{ streaming_username }}", password: "{{ streaming_password }}", flags: REPLICATION,



#  - name: Create users barman
#    postgresql_user:
#        db: postgres
#        name: barman
#        password: B29z3z4z4z1
#        role_attr_flags: SUPERUSER
#    become: yes


#  - name: get db demo
#    unarhive:
#      src: https://edu.postgrespro.ru/demo_small.zip
#      dest: /tmp
  
#  - name: load db demo
#    shell:  psql -f /tmp/demo_small.sql 



  - name: start postgresql
    systemd:
      name: postgresql-13
      state: restarted
      enabled: yes

