---

  - name: Add repo postgresql
    yum:
     name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
     state: present      
      

  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: Устанавливаем  epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install package
    yum:
     name:
      - net-tools
      - vim
      - zip
      - unzip
      - traceroute
      - mtr
      - mc
      - tcpdump
      - python-psycopg2
      - postgresql13-server


  - name: Инициализируем бд
    shell: postgresql-13-setup initdb
    ignore_errors: yes
    
  - name: start postgresql
    systemd:
      name: postgresql-13
      state: started
      enabled: yes




  - name: Create database users
    postgresql_user:
        db: postgres
        name: root
        password: B29z3z4z4z1
        role_attr_flags: SUPERUSER,LOGIN
    become: yes
    become_user: postgres
#      with_items:
#        - { name: "{{ replica_username }}", password: "{{ replica_password }}", flags: REPLICATION,LOGIN}
#        - { name: "{{ barman_username }}", password: "{{ barman_password }}", flags: SUPERUSER}
#        - { name: "{{ streaming_barman }}", password: "{{ streaming_barman_password }}", flags: REPLICATION,
