
---
- name: server
  hosts: server
  become: true
  roles:
    - role: server

- name: client
  hosts: client
  become: true
  roles:
    - role: client

- name: srv-kickstart
  hosts: srv-kickstart
  become: true
  roles:
    - role: srv-kickstart
