
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1905.1"
  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.cpus = 1
  end

  config.vm.define "r1" do |r1|
    r1.vm.network "private_network", ip: "10.0.0.1", netmask: "255.255.255.252", virtualbox__intnet: "link1"
    r1.vm.network "private_network", ip: "10.10.0.1", netmask: "255.255.255.252", virtualbox__intnet: "link2"
    r1.vm.hostname = "R1"
  end

  config.vm.define "r2" do |r2|
    r2.vm.network "private_network", ip: "10.0.0.2", netmask: "255.255.255.252", virtualbox__intnet: "link1"
    r2.vm.network "private_network", ip: "10.20.0.2", netmask: "255.255.255.252", virtualbox__intnet: "link3"
    r2.vm.hostname = "R2"
  end

  config.vm.define "r3" do |r3|
    r3.vm.network "private_network", ip: "10.10.0.2", netmask: "255.255.255.252", virtualbox__intnet: "link2"
    r3.vm.network "private_network", ip: "10.20.0.1", netmask: "255.255.255.252", virtualbox__intnet: "link3"
    r3.vm.hostname = "R3"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provisioning/net.yml"
    ansible.become = "true"
  end
end
