
---

- hosts: web
  become: true
  roles:
    - web

- hosts: backup
  become: true
  roles:
    - backup


- hosts: nagios
  become: true
  roles:
    - nagios


- hosts: logs
  become: true
  roles:
    - logs

