---
- hosts: centos
  become: true
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages

  - name: yum update
    yum:
      name: '*'
      state: latest


  - name: add zfs rpm package for <7.3 systems
    yum:
      name: http://download.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm
    state: present


  - name: install packages
    yum:
     name:
       - zfs
       - xfsdump
       - lvm2
       - mdadm
       - gdisk
       - wget
       - mc
       - screen
       - tmux
       - telnet
       - tcpdump
       - nano
       - git
       - sshpass
       - rsync
       - bc
       - ethtool
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - bind-utils
       - sshfs
       - dmidecode
       - hdparm
       - smartmontools
       - traceroute
       - net-tools
       - bmon
       - vim
       - cloud-utils-growpart

     state: latest

#  - name: Create a logical volume of 512m
#    lvol:
#      vg: otus-linux_vg0
#      lv: test
#      size: 512



#  - name: Create a logical volume of 512m with disks /dev/sda and /dev/sdb
#    lvol:
#      vg: otus-linux_vg0
#      lv: test
#      size: 512
#      pvs: /dev/sda,/dev/sdb
