# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
 config.vm.define "web" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="web"
 subconfig.vm.network 'forwarded_port', guest: 80, host: 80, host_ip: '127.0.0.1'                                                                                   
 subconfig.vm.network 'forwarded_port', guest: 443, host: 443, host_ip: '127.0.0.1'
 subconfig.vm.network :private_network, ip: "192.168.1.240"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.define "backup" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="backup"
 subconfig.vm.network :private_network, ip: "192.168.1.241"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
# second_disk = "/tmp/disk2.vmdk"
# unless File.exist?('/tmp/disk2.vmdk')
# vb.customize ['createhd', '--filename', second_disk, '--variant', 'Fixed', '--size', 5 * 1024]
# end
# vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', second_disk]
 end
 end
 config.vm.define "nagios" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="nagios
 subconfig.vm.network 'forwarded_port', guest: 80, host: 80, host_ip: '127.0.0.1'                                                                                   
 subconfig.vm.network :private_network, ip: "192.168.1.243"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.define "logs" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="logs"
 subconfig.vm.network :private_network, ip: "192.168.1.242"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.provision "ansible" do |ansible|
# ansible.compatibility_mode = "2.0"
 ansible.playbook = "provisioning/switch.yml"
 ansible.become = "true"
# ansible.tags="test"

     end
end
