# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
 config.vm.define "web" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="web"
 subconfig.vm.network :private_network, ip: "192.168.1.240"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.define "backup" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="backup"
 subconfig.vm.network :private_network, ip: "192.168.1.241"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.define "elk" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="elk"
 subconfig.vm.network :private_network, ip: "192.168.1.242"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.define "zabbix" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="zabbix"
 subconfig.vm.network :private_network, ip: "192.168.1.243"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.provision "ansible" do |ansible|
# ansible.compatibility_mode = "2.0"
 ansible.playbook = "provisioning/switch.yml"
 ansible.become = "true"
# ansible.tags="test"

     end
end