---
- hosts: vm-2
  become: true
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: start and enable firewalld
    systemd:
        name: firewalld
        state: started
        enabled: yes
    ignore_errors: yes
    tags: services



  - name: install packages
    yum:
     name:
       - autofs
       - nfs-utils
       - xfsdump
       - lvm2
       - mdadm
       - gdisk
       - wget
       - mc
       - screen
       - tmux
       - telnet
       - tcpdump
       - nano
       - git
       - sshpass
       - rsync
       - bc
       - ethtool
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - bind-utils
       - sshfs
       - dmidecode
       - hdparm
       - smartmontools
       - traceroute
       - net-tools
       - bmon
       - vim
       - cloud-utils-growpart

     state: latest

 
  - name: Create a directory /storage
    file:
      path: /storage
      state: directory
      mode: '0755'

  - name: "Добавляем данные в /etc/fstab"
    lineinfile:
      path: /etc/fstab
      regexp: ''
      line: '192.168.50.11:/mnt/upload /storage nfs vers=3,proto=udp,noatime 0 0'
    register: results
    tags: replace
    
