# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
 config.vm.define "borg-srv" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="borg-srv"
 subconfig.vm.network :"private_network", ip: "192.168.50.11"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "2024"
 vb.cpus = "1"
 end
 end
 config.vm.provision "ansible" do |ansible|
 ansible.compatibility_mode = "2.0"
 ansible.playbook = "playbook.yml"
end 
 
 config.vm.define "borg-files" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="borg-files"
 subconfig.vm.network :"private_network",  ip: "192.168.50.12"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "2024"
 vb.cpus = "1"
 end
 end
 config.vm.provision "ansible" do |ansible|
 ansible.compatibility_mode = "2.0"
 ansible.playbook = "playbook1.yml"

     end
end