version: '3.3'

networks:
  elastic:


services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    networks:
      - elastic
    depends_on:
      - kibana
    volumes:
      - ./nginx/hosts/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/hosts/proxy-params.conf:/etc/nginx/proxy-params.conf
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
      - NGINX_WORKERS=4
      - NGINX_CONFIG=*
                       


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    restart: always
    container_name: "elasticsearch"

    networks:
      - elastic

    volumes:
     - ./elasticsearch/data:/usr/share/elasticsearch/data
     - /etc/localtime:/etc/localtime:ro
     - ./elasticsearch/logs:/usr/share/elasticsearch/logs
     - ./elasticsearch/conf.d/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - "ES_LOGGER_LEVEL=${ES_LOGGER_LEVEL}"
#    ulimits:
#      memlock:
#        soft: ${ULIM_MEMLOCK_SOFT}
#        hard: ${ULIM_MEMLOCK_HARD}
#    mem_limit: 4g
    ports:
      - 9200:9200
      - 9300:9300



 # filebeat:
#    image: docker.elastic.co/beats/filebeat:7.5.1
#    container_name: filebeat
#    hostname: ${HOSTNAME}
#    restart: always
#    ports:
#      - 5514:5514/udp
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - ./filebeat/data:/usr/share/filebeat/data


  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    restart: always
    container_name: "logstash"
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./logstash/settings/:/usr/share/logstash/config/
      - ./logstash/log/:/var/log/logstash/
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - elastic
#    environment:
#      XPACK_MONITORING_ENABLED: "true" 
    

  kibana:
    image: kibana:7.8.1
    container_name: kibana
    restart: always
    networks:
      - elastic
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./kibana/conf.d/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch


  heartbeat:  
    image: docker.elastic.co/beats/heartbeat:7.8.1
    container_name: "heartbeat"
    restart: always
    networks:
      - elastic
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - --name=heartbeat 
      - --user=heartbeat
      - --strict.perms=false -e 
    volumes:
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    depends_on:
      - elasticsearch

