---
- hosts: client
  become: true
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no

  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled
    tags: selinux

  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    ignore_errors: yes
    tags: services

  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages

#  - name: yum update
#    yum:
#      name: '*'
#      state: latest


  
  - name: Install borg
    get_url:
      url: https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64
      dest: /usr/bin/borg
      owner: root
      group: root
      mode: '0777'

  - name: Add user for borg
    user:
      name: borg
      home: /home/borg
      comment: BorgBackup
      
  - name: Create a directory Log borg
    file:
      path: /var/log/borg/
      state: directory
      mode: '0775'

  
  - name: Create file log borg
    file:
      path: /var/log/borg/borg.log
      owner: root
      group: root
      mode: '0775'
      state: touch
 


  - name: install packages
    yum:
     name:
       - wget
       - mc
       - screen
       - tmux
       - telnet
       - tcpdump
       - ethtool
       - yum-utils
       - ncdu
       - htop
       - lsof
       - bzip2
       - zip
       - unzip
       - bind-utils
       - traceroute
       - net-tools
       - vim

     state: latest



  - name: Генерируем открытый и закрытый ключ rsa
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

