
---

- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes


- name: restart bareos-dir
  systemd:
    name: bareos-dir
    state: restarted
    enabled: yes


- name: restart nrpe
  systemd:
    name: nrpe
    state: restarted
    enabled: yes
