version: '3'
networks:
 php:
 nginx:

services:
 web:
  image: nginx:latest
  container_name: "nginx_kos"
  depends_on:
    - php
  ports:
    - "80:80"
  networks:
    - php
  volumes:
    - ./hosts:/etc/nginx/
    - ./www:/var/www/
    - ./logs/nginx:/var/log/nginx

 php:
  build: ./php
  container_name: "php_kos"
  networks:
    - nginx
#  ports:
#    - "9000:9000"
  volumes:
    - ./www:/var/www/