version: '3'
networks:
 php:
 nginx:

services:
 web:
  image: impkos/nginx:latest
  container_name: "nginx_kos"
  depends_on:
    - php
  ports:
    - "80:80"
  networks:
    - php
  volumes:
    - ./hosts/nginx.conf:/etc/nginx/nginx.conf
    - ./code:/code
    - ./logs/nginx:/var/log/nginx

 php:
  image: impkos/php:latest
  container_name: "php_kos"
  networks:
    - php
  ports:
    - "9000:9000"
  volumes:
    - ./code:/code