
- name: Add multiple repositories
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no


- name: install epel-release
  yum:
    name:
      - epel-release
    state: latest
                    


- name: wget bareos repos
  get_url:
    url: http://download.bareos.org/bareos/release/latest/CentOS_7/bareos.repo
    dest: /etc/yum.repos.d/bareos.repo
  tags: install-packages

- name: install packages bareos-fd
  yum:
    name:
      - net-tools
      - mariadb-server
      - mariadb
      - mc
      - vim
      - bareos
      - htop
      - nrpe
      - nagios-plugins-nrpe
      - nagios-plugins-all
      - nagios-plugins
      - bc
                                        

- name: start and enable firewalld
  systemd:
   name: firewalld
   state: started
   enabled: yes




- name: "firewalld 443 tcp"
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled


- name: "firewalld 9101 tcp"
  firewalld:
    port: 9101/tcp
    permanent: yes
    state: enabled


- name: "firewalld 9102 tcp"
  firewalld:
    port: 9102/tcp
    permanent: yes
    state: enabled


- name: "firewalld 9103 tcp"
  firewalld:
    port: 9103/tcp
    permanent: yes
    state: enabled


- name: "firewalld 80 tcp"
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: "firewalld 5666 tcp"
  firewalld:
    port: 5666/tcp
    permanent: yes
    state: enabled


- name: "firewalld 3306 tcp"
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled



- name: "firewalld reload"
  shell: "firewall-cmd --reload"





- name: copy nrpe.cfg for nagios
  copy:
    src: files/nrpe.cfg
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644


- name: copy plugins
  copy:                    
    src: files/plugins/{{ item }} 
    dest: /usr/lib64/nagios/plugins/
    owner: root            
    group: root            
    mode: 0755             
  with_items:
    - check_cpu
    - check_ram
  notify:                  
    - restart nrpe



- name: Create a directory /storage/backup
  file:
    path: /storage/backup
    state: directory
    owner: 'bareos'
    group: 'bareos'
    mode: '0755'
  
    
#- name: Create filesystem xfs /dev/sdb
#  filesystem:
#    fstype: xfs
#    dev: /dev/sdb
        
    
#- name: Mount /storage/backup
#  mount:
#    path: /storage/backup
#    src: /dev/sdb
#    opts: rw
#    state: mounted
#    fstype: xfs




- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes




- name: run script create db,tables,privileges
  shell: |
    /usr/lib/bareos/scripts/create_bareos_database
    /usr/lib/bareos/scripts/make_bareos_tables
    /usr/lib/bareos/scripts/grant_bareos_privileges


- name: start bareos-dir
  systemd:
    name: bareos-dir
    state: started
    enabled: yes



- name: copy bareos conf
  copy:
    src: files/bareos
    dest: /etc/
    owner: bareos
    group: bareos
    mode: 0755
  notify:
    - restart bareos-dir
 

- name: start bareos-sd
  systemd:
    name: bareos-sd
    state: started
    enabled: yes




- name: start nrpe
  systemd:
    name: nrpe
    state: started
    enabled: yes




#- name: replace pass bareos-fd
#  replace:
#    path: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
#    regexp: '(?i)Password = (.*)$'
#    replace: 'Password = "bapUaOfXWQKHSV7DH/Fn0goFfWyDGulOffsst4xDM9GQ"'
#  register: results
#  tags: password

#- debug:
#    var: results

