# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "provisioning/openvpn.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.10.10"
    server.vm.hostname = "server.loc"
  end


  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.10.20"
    client.vm.hostname = "client.loc"
  end

    config.vm.define "openvpnsrv" do |openvpnsrv|
    openvpnsrv.vm.network "private_network", ip: "192.168.10.30"
    openvpnsrv.vm.hostname = "openvpnsrv"
  end

    config.vm.define "ocserv" do |ocserv|
    ocserv.vm.network "private_network", ip: "192.168.10.40"
    ocserv.vm.hostname = "ocserv"
  end



end
