# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "provisioning/openvpn.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "openvpnsrv" do |openvpnsrv|
    openvpnsrv.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "vpn"
    openvpnsrv.vm.hostname = "openvpnsrv"
  end


  config.vm.define "openvpncl" do |openvpncl|
    openvpncl.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "vpn"
    openvpncl.vm.hostname = "openvpncl"
  end


end
