
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1905.1"
  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.cpus = 1
  end

  config.vm.define "inetRouer" do |inetRouer|
    inetRouer.vm.network "private_network", ip: "10.0.0.1", virtualbox__intnet: "link1"
    inetRouer.vm.hostname = "inetRouer"
  end

  config.vm.define "inetRouer2" do |inetRouer2|
    inetRouer2.vm.network "private_network", ip: "10.0.0.2", virtualbox__intnet: "link1"
    inetRouer2.vm.hostname = "inetRouer2"
  end

  config.vm.define "centralServer" do |centralServer|
    centralServer.vm.network "private_network", ip: "10.0.0.3", virtualbox__intnet: "link1"
    centralServer.vm.hostname = "centralServer"
  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "provisioning/iptables.yml"
#    ansible.become = "true"
#  end
end