---

  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install openvpn
    yum:
     name:
      - net-tools
      - zip
      - unzip
      - openssl
      - wget
      - mc
      - easy-rsa
      - iperf3


  - name: net.ipv4.ip_forward = 1
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes



