
---

- hosts: master
  become: true
  roles:
    - master
#  vars: 
#    ansible_python_interpreter: python3

- hosts: slave
  become: true
  roles:
    - slave




- hosts: barman
  become: true
  roles:
    - barman


