  - name: repository openvpn
    yum_repository:
      name: openvpn
      description: repo_openvpn
      baseurl: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn-beta/epel-7-$basearch/
      skip_if_unavailable: yes
      gpgcheck: 1
      gpgkey: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn-beta/pubkey.gpg
      enabled: yes



  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install openvpn
    yum:
     name:
      - zip
      - unzip
      - openssl
      - wget
      - mc
      - openvpn
      - openvpn-devel
      - easy-rsa
      - iperf3
#    notify:
#      - start openvpn
    ignore_errors: yes


  - name: Create a directory ccd
    file:
      path: /etc/openvpn/{{ item }}
      state: directory
      mode: '0755'
    with_items:
    - "ccd/"
    - "keys/"
    - "scripts/"
               
               

  - name: Create a symbolic link
    file:
      src: /usr/share/easy-rsa/3.0.7/
      dest: /etc/openvpn/server/3.0.7
      owner: root
      group: root
      state: link

  - name: template server.conf
    template:
      src:  templates/server.conf.j2
      dest: /etc/openvpn/server/server.conf
      mode: '0755'




  - name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes




  - name: easyrsa init-pki
    shell: ./easyrsa init-pki
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: easyrsa gen-dh
    shell: ./easyrsa gen-dh
    args:
        chdir: /etc/openvpn/server/3.0.7



  - name: easyrsa ca
    shell:  echo server | ./easyrsa build-ca nopass
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: easyrsa server.crt ans server.key
    shell: ./easyrsa build-server-full server nopass
    args:
        chdir: /etc/openvpn/server/3.0.7






