output.elasticsearch:
  hosts: ["<es_url>"]
    username: "elastic"
      password: "<password>"
      setup.kibana:
        host: "<kibana_url>"


filebeat.inputs:
- type: syslog
  protocol.udp:
    host: "0.0.0.0:5514"
  enabled: true
  tags: [ "cisco" ]
  processors:
    - drop_event:
        when:
          contains:
