# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
 config.vm.define "web" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="web"
 subconfig.vm.network :"private_network",  ip: "192.168.50.13"
 subconfig.vm.network "forwarded_port", adapter: 1, guest: 8081, host: 8081, host_ip: '127.0.0.1'
 subconfig.vm.network "forwarded_port", adapter: 1, guest: 8082, host: 8082, host_ip: '127.0.0.1'
 subconfig.vm.network "forwarded_port", adapter: 1, guest: 8083, host: 8083, host_ip: '127.0.0.1'
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "1024"
 vb.cpus = "1"
 end
 config.vm.provision "ansible" do |ansible|
 ansible.compatibility_mode = "2.0"
 ansible.playbook = "provisioning/switch.yml"
end
end
end


