# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
 config.vm.define "web" do |subconfig|
 subconfig.vm.box = "centos/7"
 subconfig.vm.hostname="web"
 subconfig.vm.network 'forwarded_port', guest: 80, host: 80, host_ip: '127.0.0.1'
 subconfig.vm.network 'forwarded_port', guest: 8080, host: 8080, host_ip: '127.0.0.1'
 subconfig.vm.network 'forwarded_port', guest: 8081, host: 8081, host_ip: '127.0.0.1'
 subconfig.vm.network :private_network, ip: "192.168.1.240"
 subconfig.vm.provider "virtualbox" do |vb|
 vb.memory = "256"
 vb.cpus = "1"
 end
 end
 config.vm.provision "ansible" do |ansible|
 ansible.compatibility_mode = "2.0"
 ansible.playbook = "provisioning/switch.yml"
 ansible.become = "true"
# ansible.tags="test"

     end
end