
---
- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes


- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes


- name: restart nrpe
  systemd:
    name: nrpe
    state: restarted
    enabled: yes


- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
