---

  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest


  
  - name: install packages
    yum:
     name:
       - ethtool
       - mc
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - net-tools
       - vim
     state: latest



  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled


  - name: Создаем каталог ~root/.ssh/
    file:
     path: /root/.ssh
     state: directory
     owner: root
     group: root
     mode: '700'



  - name: Копируем приватный ключ клиента в домашний каталог ~root/.ssh/
    copy:
     src:  files/id_rsa
     dest: /root/.ssh/
     group: root
     owner: root
     mode: '600'

  - name: И обновляем known_hosts, чтобы избавиться от запроса подтверждения при первичном подключении
    raw: ssh-keyscan -t rsa server >> /root/.ssh/known_hosts


