---
- hosts: web
  become: true
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no




  - name: nginx repo
    yum_repository:
      name: nginx
      description: nginx repo
      file: nginx
      baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: 0
      enabled: 1




  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: start and enable firewalld
    systemd:
        name: firewalld
        state: stopped
        enabled: no
    ignore_errors: yes
    tags: services


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled
    tags: selinux




  - name: install packages
    yum:
     name:
       - ethtool
       - mc
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - net-tools
       - vim
       - nginx
       
     state: latest


  - name: start and enable nginx
    systemd:
        name: nginx
        state: started
        enabled: yes
    ignore_errors: yes
    tags: services
 
