---
- hosts: log
  become: true
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no



  - name: set up docker stable repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    tags: docker


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled
    tags: selinux

  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    ignore_errors: yes
    tags: services

  - name: install docker
    yum:
     name:
      - docker-ce
      - docker-compose
    tags: docker




  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages

  - name: yum update
    yum:
      name: '*'
      state: latest


  - name: install packages
    yum:
     name:
       - wget
       - mc
       - screen
       - tmux
       - telnet
       - tcpdump
       - ethtool
       - yum-utils
       - ncdu
       - htop
       - lsof
       - bzip2
       - zip
       - unzip
       - bind-utils
       - smartmontools
       - traceroute
       - net-tools
       - vim

     state: latest

 
  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes
    tags: docker
 
