  - name: repository openvpn
    yum_repository:
      name: openvpn
      description: repo_openvpn
      baseurl: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn-beta/epel-7-$basearch/
      skip_if_unavailable: yes
      gpgcheck: 1
      gpgkey: https://download.copr.fedorainfracloud.org/results/dsommers/openvpn-beta/pubkey.gpg
      enabled: yes



  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install openvpn
    yum:
     name:
      - net-tools
      - zip
      - unzip
      - openssl
      - wget
      - mc
      - openvpn
      - openvpn-devel
      - easy-rsa
      - iperf3


  - name: Create a directory ccd
    file:
      path: /etc/openvpn/{{ item }}
      state: directory
      mode: '0755'
    with_items:
    - "ccd/"
    - "keys/"
    - "scripts/"
               

  
  - name: Copy client route
    copy:
      src:  files/client
      dest: /etc/openvpn/ccd/client
      group: root
      owner: root
      mode: '775'


  
               

  - name: Create a symbolic link
    file:
      src: /usr/share/easy-rsa/3.0.7/
      dest: /etc/openvpn/server/3.0.7
      owner: root
      group: root
      state: link



  - name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes




  - name: easyrsa init-pki
    shell: ./easyrsa init-pki
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: easyrsa build-ca
    shell: echo 'rasvpn' | ./easyrsa build-ca nopass
    args:
        chdir: /etc/openvpn/server/3.0.7



  - name: easyrsa gen-req
    shell:  echo 'rasvpn' | ./easyrsa gen-req server nopass
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: easyrsa server.crt ans server.key
    shell: echo 'yes' | ./easyrsa sign-req server server
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: gen dh.pem
    shell: ./easyrsa gen-dh
    args:
        chdir: /etc/openvpn/server/3.0.7



  - name: gen client.crt
    shell: echo 'client' | ./easyrsa gen-req client nopass
    args:
        chdir: /etc/openvpn/server/3.0.7


  - name: gen client.key
    shell: echo 'yes' | ./easyrsa sign-req client client
    args:
        chdir: /etc/openvpn/server/3.0.7







  - name: template server.conf
    template:
      src:  templates/server.conf.j2
      dest: /etc/openvpn/server/server.conf
      mode: '0755'




  - name: start openvpn-server unit
    systemd:
      name: openvpn-server@server
      state: restarted
      enabled: yes
               
