---


  - name: install yum groupinstall "Development Tools"
    shell: yum groupinstall "Development Tools" -y


  - name: install epel-release
    shell: yum --enablerepo=extras install epel-release -y


  - name: install package python
    yum:
     name:
      - python-devel
      - python-pip
      - python3-pip
      - vim
      - mc




  - name: Install pip uwsgi 
    pip:
      name: 
       - uwsgi


  - name: install pip django
    shell: python -m pip install "django<2"


  - name: install project django
    shell: django-admin startproject dj
    args:
      chdir: /
    ignore_errors: yes


  - name: install pip django
    shell: python manage.py migrate
    args:
      chdir: /dj
    ignore_errors: yes




  - name: copy default.conf for django
    copy:
      src: files/dj/dj.ini
      dest: /dj/dj.ini
      owner: root
      group: root
      mode: 0755


  - name: copy wsgi.py and settings.py
    copy:
      src: files/dj/dj/{{ item }}
      dest: /dj/dj/
      owner: root
      group: root
      mode: 0755
    with_items:
      - wsgi.py
      - settings.py
                

  
  
#  - name: install pip django
#    shell: python manage.py runserver 0.0.0.0:8000


#  - name: copy uwsgi.conf for nginx
#    copy:
#      src: files/default.conf
#      dest: /etc/nginx/conf.d/django.conf
#      owner: root
#      group: root
#      mode: 0644
#    notify:
#      - restart nginx


  - name: copy uwsgi.service
    copy:
      src: files/uwsgi.service
      dest: /etc/systemd/system/uwsgi.service
      owner: root
      group: root
      mode: 0755

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload



  - name: start  uwsgi
    systemd:
      name: uwsgi
      state: started
      enabled: yes
                