---


  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest

  
  - name: install packages
    yum:
     name:
       - ethtool
       - mc
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - net-tools
       - vim
       - dhcp
       - tftp
       - syslinux-tftpboot.noarch
       - tftp-server
       - xinetd
       - cobbler
       - nginx
       - net-tools
     state: latest

  

  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled


  - name: Добавляем публичный ключ клиента для возможности захода на сервер без пароля
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', './files/id_rsa.pub') }}"


#  - name: Create a new primary partition with a size of 1GiB
#    parted:
#      device: /dev/sdb
#      number: 1
#      state: present
#      part_end: 2GiB


 
#  - name: Create filesystem xfs /dev/sdb
#    filesystem:
#      fstype: xfs
#      dev: /dev/sdb1
  


  - name: Ставим свой конфиг nginx
    copy:
      src:  files/nginx.conf
      dest: /etc/nginx/
      group: root
      owner: root
      mode: '775'
        




   
  - name: Создаем каталог /point
    file:
      path: /point
      state: directory
      mode: '0775'
 
   

  
#  - name: Download CentOS Minimal
#    get_url:
#      url: http://centos-mirror.rbc.ru/pub/centos/8.2.2004/isos/x86_64/CentOS-8.2.2004-x86_64-minimal.iso
#      dest: /point
#      mode: '0777'

  
#  - name: Mount iso
#    raw: mount -t iso9660 /point/CentOS-8.2.2004-x86_64-minimal.iso /mnt -o loop,ro



  - name: Копируем dhcp.conf
    copy:
      src:  files/dhcpd.conf
      dest: /etc/dhcp
      group: root
      owner: root
      mode: '775'





  - name: Копируем все файлы из каталога /html для доступ по http
    copy:
      src:  /mnt/
      dest: /usr/share/nginx/html
      remote_src: yes
      group: root
      owner: root
      mode: '775'



  - name: "RPM"
    shell: rpm2cpio syslinux-tftpboot-6.04-4.el8.noarch.rpm | cpio -dimv
    args:
        chdir: /usr/share/nginx/html/BaseOS/Packages
        
        
  - name: Создаем каталог pxelinux/pxelinux.cfg и rawhide-x86_64
    file:
      path: /var/lib/tftpboot/pxelinux/{{ item }}
      state: directory
      mode: '0775'
    with_items:
    - "pxelinux.cfg/"
    - "images/"




  - name: Копируем файлы в каталог pxelinux
    copy:
      src:  /point/tftpboot/{{ item }}
      dest: /var/lib/tftpboot/pxelinux/
      remote_src: yes
      group: root
      owner: root
      mode: '775'
    with_items:
    - "pxelinux.0"
    - "libcom32.c32"
    - "ldlinux.c32"
    - "vesamenu.c32"
  
        
  - name: Копируем default в каталог pxelinux.cfg
    copy:
      src:  files/default
      dest: /var/lib/tftpboot/pxelinux/pxelinux.cfg
      group: root
      owner: root
      mode: '775'
        

  - name: Копируем изображение заставки в корневой каталог tftp
    copy:
      src:  /usr/share/nginx/html/images/pxeboot/{{ item }}
      dest: /var/lib/tftpboot/pxelinux/images
      remote_src: yes
      group: root
      owner: root
      mode: '775'
    with_items:
    - "vmlinuz"
    - "initrd.img"
        


  - name: start unit all
    systemd:
      state: started
      enabled: yes
      name: "{{ item }}"
    with_items:
      - tftp.service
      - dhcpd.service
      - xinetd.service
      - nginx.service
  