---


  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest

  
  - name: install packages
    yum:
     name:
       - ethtool
       - mc
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - net-tools
       - vim
       - dhcp
       - tftp
       - syslinux-tftpboot.noarch
       - tftp-server
     state: latest

  

  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled


  - name: Добавляем публичный ключ клиента для возможности захода на сервер без пароля
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', './files/id_rsa.pub') }}"

   
  - name: Создаем каталог /point
    file:
      path: /point
      state: directory
      mode: '0775'
 
   

  
  - name: Download CentOS Minimal
    get_url:
      url: https://mirror.yandex.ru/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-Minimal-2003.iso
      dest: /point
      mode: '0440'

  
  - name: Mount /mnt
    mount:
      path: /point/CentOS-7-x86_64-Minimal-2003.iso
      src: /mnt
      opts: rw
      state: mounted
      fstype: iso9660



  - name: Копируем dhcp.conf
    copy:
      src:  files/dhcpd.conf
      dest: /etc/dhcp
      group: root
      owner: root
      mode: '775'




  - name: start dhcpd
    systemd:
      name: dhcpd
      state: started
      enabled: yes

  



  - name: Создаем каталог pxelinux/images/CentOS
    file:
      path: /var/lib/tftpboot/pxelinux/images
      state: directory
      mode: '0775'


  - name: Копируем pxelinux.cfg
    copy:
      src:  files/pxelinux.cfg
      dest: /var/lib/tftpboot/pxelinux/
      group: root
      owner: root
      mode: '775'


  - name: start tftp
    systemd:
      name: tftp
      state: started
      enabled: yes


  
