---


  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: install epel-release
    yum:
     name:
      - epel-release
     state: latest

  
  - name: install packages
    yum:
     name:
       - ethtool
       - mc
       - yum-utils
       - ncdu
       - htop
       - lsof
       - lshw
       - iotop
       - iftop
       - atop
       - bzip2
       - zip
       - unzip
       - net-tools
       - vim
       - dhcp
       - tftp
       - syslinux-tftpboot.noarch
       - tftp-server
     state: latest

  

  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: disable selinux
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled


  - name: Добавляем публичный ключ клиента для возможности захода на сервер без пароля
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', './files/id_rsa.pub') }}"


  - name: Копируем dhcp.conf
    copy:
      src:  files/dhcpd.conf
      dest: /etc/dhcp
      group: root
      owner: root
      mode: '775'




  - name: start dhcpd
    systemd:
      name: dhcpd
      state: started
      enabled: yes

