---


  - name: Create a directory .ssh
    file:
      path: /root/.ssh
      state: directory
      mode: '0700'


  - name: Copy id_rsa and authorized_keys
    copy:
      src: files/keys/
      dest: /root/.ssh/
      owner: root
      group: root
      mode: '0600'



  - name: restart sshd
    systemd: 
      name: sshd
      state: restarted


  - name: add "{{ ip }} {{ dns }}" to hosts
    lineinfile:
      path: /etc/hosts
      state: present
      line: '192.168.11.150  master'




  - name: Add repo postgresql
    yum:
     name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
     state: present      
      

  - name: Add multiple repositories 
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no


  - name: Устанавливаем  epel-release
    yum:
     name:
      - epel-release
     state: latest
    tags: install-packages


  - name: Disable SELinux
    selinux:
      state: disabled


  - name: stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no


  - name: install package
    yum:
     name:
      - net-tools
      - vim
      - zip
      - unzip
      - traceroute
      - mtr
      - mc
      - tcpdump
      - python-psycopg2
      - barman


  - name: set barman configuration
    copy:
      src: files/barman.conf
      dest: /etc/barman.conf
      mode: 0644

  - name: set backup configuration
    copy:
      src: files/master.conf
      dest: /etc/barman.d/master.conf
      mode: 0644


  - name: store connection info for barman
    template:
      src: templates/.pgpass
      dest: /var/lib/barman/.pgpass
      mode: 0600
      owner: barman
      group: barman


  - name: barman switch-wal --force --archive master
    shell: barman switch-wal --force --archive master
    ignore_errors: yes
            
